<?php
  // DO NOT EDIT THIS FILE; IT AUTOMATICALLY LOADS INDEX.HTML
  // ALLOWS FOR CORRECT HEROKU SERVER DEPLOYMENT USING PHP
  header( 'Location: index.html' );
  exit();
?>
Contact GitHub API Training Shop Blog About
